---
title: "Normal Distribution Practice"
subtitle: "Lab 03"
author: "YOUR NAME HERE"
format:
  html:
    self-contained: true
    toc: true
    toc_float: true
    number_section: false
    highlight: tango
editor: visual
editor_options:
  chunk_output_type: console
---

## Exercise 1

a\. YOUR ANSWER HERE

b\. YOUR ANSWER HERE

c\. YOUR ANSWER HERE

d\. YOUR ANSWER HERE

## Exercise 2

a\. YOUR ANSWER HERE

b\. YOUR ANSWER HERE

## Exercise 3

```{r}
# part a code 


# part b code 


# part c code 


# part d code 


# part e code 


# part f code 



```

## Exercise 4

```{r}
# part a code 


# part b code 


# part c code 


# part d code 



```

e\. YOUR ANSWER HERE

f\. YOUR ANSWER HERE

## Exercise 5

```{r}
# part a code 


# part b code 


# part c code 



```

d\. YOUR ANSWER HERE

## Exercise 6

```{r}
# part a code 


# part b code 


# part c code 


# part d code 


# part e code 


# part f code 


# part g code 


# part h code 



```

i\. YOUR ANSWER HERE

j\. YOUR ANSWER HERE
